CREATE TABLE `performer` (
  `PERFORMER_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NULL DEFAULT NULL,
  `STATUS` INT(11) NULL DEFAULT NULL,
  `TYPE` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`PERFORMER_ID`)
)
  COLLATE='utf8_general_ci'
  ENGINE=InnoDB;

CREATE TABLE `task` (
  `TASK_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATION_TIME` DATETIME NULL DEFAULT NULL,
  `NAME` VARCHAR(255) NULL DEFAULT NULL,
  `PRIORITY` INT(11) NULL DEFAULT NULL,
  `STATUS` INT(11) NULL DEFAULT NULL,
  `TYPE` INT(11) NULL DEFAULT NULL,
  `PERFORMER_ID` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`TASK_ID`),
  INDEX `FK272D85E2E492FD` (`PERFORMER_ID`),
  CONSTRAINT `FK272D85E2E492FD` FOREIGN KEY (`PERFORMER_ID`) REFERENCES `performer` (`PERFORMER_ID`)
)
  COLLATE='utf8_general_ci'
  ENGINE=InnoDB;
